<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9a4071495ac4edb1f8b19d4f85e0fcdf
{
    public static $files = array (
        '253c157292f75eb38082b5acb06f3f01' => __DIR__ . '/..' . '/nikic/fast-route/src/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'FastRoute\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FastRoute\\' => 
        array (
            0 => __DIR__ . '/..' . '/nikic/fast-route/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9a4071495ac4edb1f8b19d4f85e0fcdf::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9a4071495ac4edb1f8b19d4f85e0fcdf::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9a4071495ac4edb1f8b19d4f85e0fcdf::$classMap;

        }, null, ClassLoader::class);
    }
}
